cmake_minimum_required(VERSION 3.16)
project(m0609_moveit_sim)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(rclcpp_action REQUIRED)
find_package(moveit_ros_planning_interface REQUIRED)
find_package(moveit_ros_planning REQUIRED)
find_package(moveit_core REQUIRED)
find_package(yaml_cpp_vendor REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(std_msgs REQUIRED)
find_package(control_msgs REQUIRED)
find_package(trajectory_msgs REQUIRED)
add_executable(moveit_step src/moveit_step.cpp)
target_compile_features(moveit_step PUBLIC cxx_std_17)
ament_target_dependencies(moveit_step rclcpp rclcpp_action moveit_ros_planning_interface moveit_ros_planning moveit_core std_msgs control_msgs trajectory_msgs)
target_link_libraries(moveit_step yaml-cpp)
install(TARGETS moveit_step DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch DESTINATION share/${PROJECT_NAME})
add_executable(perf_replay src/perf_replay.cpp)
target_compile_features(perf_replay PUBLIC cxx_std_17)
ament_target_dependencies(perf_replay rclcpp rclcpp_action moveit_ros_planning_interface moveit_ros_planning moveit_core std_msgs control_msgs trajectory_msgs)
target_link_libraries(perf_replay yaml-cpp)
install(TARGETS perf_replay DESTINATION lib/${PROJECT_NAME})
ament_package()
